[package]
name = "arp-scanner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnetwork = "0.20.0"
pnet = "0.34.0"
tokio = { version = "1.37.0", features = ["full"] } 
